-- Index in Oracle
/*

An index in SQL is a database object that improves the speed of data retrieval on a table by creating a 
data structure (like a B-tree or hash table) that allows quick lookups for specified columns.

Link: https://www.oracletutorial.com/oracle-index/

Benefits of Using Indexes
- Speeds up queries with SELECT, WHERE, JOIN, ORDER BY, or GROUP BY clauses that filter or sort by emp_name.
    For example: `SELECT * FROM employees WHERE emp_name = 'John Doe';`



*/

CREATE INDEX index_name ON table_name(column1[,column2,...]);

`CREATE INDEX:` This command creates a new index.
`index_name:` The name of the index.
`ON table_name(column1[,column2,...]):` The table and column(s) that the index is created on. 



CREATE TABLE members(
    member_id INT GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    gender CHAR(1) NOT NULL,
    dob DATE NOT NULL,
    email VARCHAR2(255) NOT NULL,
    PRIMARY KEY(member_id)
);

-- https://www.oracletutorial.com/wp-content/uploads/2019/01/load_member_data.txt

SELECT 
    index_name, 
    index_type, 
    visibility, 
    status 
FROM 
    all_indexes
WHERE 
    table_name = 'MEMBERS';


CREATE INDEX members_last_name_i 
ON members(last_name);

SELECT * FROM members
WHERE last_name = 'Harse';

CREATE UNIQUE INDEX index_name ON 
table_name(column1[,column2,...]);

DROP INDEX [schema_name.]index_name;

